[package]
name = "grid_walker"
version = "0.1.0"
authors = ["James Wood <darkgalac@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quicksilver = "=0.4.0-alpha0.2"
rand="0.7.3"
